# fly.toml app configuration file generated for pico-pico-pic on 2023-06-20T10:14:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pico-pico-pic"
primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
